src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_omdb;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_wikipedia;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdOmdb(): ?int
    {
        return $this->id_omdb;
    }

    public function setIdOmdb(int $id_omdb): self
    {
        $this->id_omdb = $id_omdb;

        return $this;
    }

    public function getIdWikipedia(): ?int
    {
        return $this->id_wikipedia;
    }

    public function setIdWikipedia(int $id_wikipedia): self
    {
        $this->id_wikipedia = $id_wikipedia;

        return $this;
    }
}

src/Form/MovieType.php
<?php

namespace App\Form;

use App\Entity\Movie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MovieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id_omdb')
            ->add('id_wikipedia')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Movie::class,
        ]);
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Form\MovieType;
use App\Repository\MovieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/movie")
 */
class MovieController extends AbstractController
{
    /**
     * @Route("/", name="movie_index", methods={"GET"})
     */
    public function index(MovieRepository $movieRepository): Response
    {
        return $this->render('movie/index.html.twig', [
            'movies' => $movieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="movie_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $movie = new Movie();
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($movie);
            $entityManager->flush();

            return $this->redirectToRoute('movie_index');
        }

        return $this->render('movie/new.html.twig', [
            'movie' => $movie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="movie_show", methods={"GET"})
     */
    public function show(Movie $movie): Response
    {
        return $this->render('movie/show.html.twig', [
            'movie' => $movie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="movie_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Movie $movie): Response
    {
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('movie_index');
        }

        return $this->render('movie/edit.html.twig', [
            'movie' => $movie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="movie_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Movie $movie): Response
    {
        if ($this->isCsrfTokenValid('delete'.$movie->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($movie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('movie_index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/movie/_delete_form.html.twig
<form method="post" action="{{ path('movie_delete', {'id': movie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ movie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/movie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/movie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Movie{% endblock %}

{% block body %}
    <h1>Edit Movie</h1>

    {{ include('movie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('movie_index') }}">back to list</a>

    {{ include('movie/_delete_form.html.twig') }}
{% endblock %}

templates/movie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movie index{% endblock %}

{% block body %}
    <h1>Movie index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_omdb</th>
                <th>Id_wikipedia</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for movie in movies %}
            <tr>
                <td>{{ movie.id }}</td>
                <td>{{ movie.idOmdb }}</td>
                <td>{{ movie.idWikipedia }}</td>
                <td>
                    <a href="{{ path('movie_show', {'id': movie.id}) }}">show</a>
                    <a href="{{ path('movie_edit', {'id': movie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('movie_new') }}">Create new</a>
{% endblock %}

templates/movie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Movie{% endblock %}

{% block body %}
    <h1>Create new Movie</h1>

    {{ include('movie/_form.html.twig') }}

    <a href="{{ path('movie_index') }}">back to list</a>
{% endblock %}

templates/movie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movie{% endblock %}

{% block body %}
    <h1>Movie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ movie.id }}</td>
            </tr>
            <tr>
                <th>Id_omdb</th>
                <td>{{ movie.idOmdb }}</td>
            </tr>
            <tr>
                <th>Id_wikipedia</th>
                <td>{{ movie.idWikipedia }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('movie_index') }}">back to list</a>

    <a href="{{ path('movie_edit', {'id': movie.id}) }}">edit</a>

    {{ include('movie/_delete_form.html.twig') }}
{% endblock %}